'use client';
import {useEffect,useState,useCallback} from 'react';
import {Plus, Search, LayoutGrid, CheckCheck, FileCheck2, Lightbulb, ArrowUpRight, LockKeyhole, RefreshCw, Flag, ClipboardList, CircleHelp, X, CalendarDays} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {Item,statuses,kinds,areas,canadaOnlyIds,pilotFeatureIds} from '@/lib/board';
import MobileAcceptance from './mobile-acceptance'; import ReleaseHistory from './release-history';
import PilotRunbook from './pilot-runbook';
import PilotReadiness from './pilot-readiness';
import EvidenceCapture from './evidence-capture';
function Choice({value,onChange,options,label}:{value:string;onChange:(x:string)=>void;options:readonly string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
const fresh=():Item=>({id:'',title:'',description:'',status:'Ready to build',kind:'Task',area:'Foundation',priority:'Medium',release:'MVP',owner:'',criteria:'',notes:'',dependencies:'',due:'',version:0,updated:''});
export default function Page(){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState('board'),[scope,setScope]=useState('Mola first'),[query,setQuery]=useState(''),[area,setArea]=useState('All areas'),[priority,setPriority]=useState('All priorities'),[draft,setDraft]=useState<Item|null>(null),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[drag,setDrag]=useState<string|null>(null);
 const load=useCallback(async()=>{setError('');try{const r=await fetch('/api/items');const d:any=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const save=useCallback(async(item:Item)=>{const uncertain='The save could not be confirmed. Your details are still here. Refresh the board and check the item before trying again; it may already have been saved.';let r:Response;try{r=await fetch('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});}catch{throw new Error(uncertain);}const d:any=await r.json().catch(()=>null);if(r.status>=500||(r.ok&&(!d?.item||typeof d.item.id!=='string'||!Number.isInteger(d.item.version))))throw new Error(uncertain);if(!r.ok)throw new Error(d?.error||'The item could not be updated. Refresh and try again.');setItems(prev=>prev.some(x=>x.id===d.item.id)?prev.map(x=>x.id===d.item.id?d.item:x):[...prev,d.item]);return d.item as Item;},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const a=new AbortController();try{Promise.resolve(ctx.registerTool({name:'list_development_items',title:'List development items',description:'Read the current development tasks, decisions, tests, and future ideas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {items:items.map(({id,title,status,kind,release})=>({id,title,status,kind,release}))};}},{signal:a.signal})).catch(()=>{});}catch{}return()=>a.abort();},[items]);
 const edit=(x:Item)=>{setSaveError('');setDraft({...x});};
 const add=()=>{const x=fresh();if(view==='decisions'){x.kind='Decision';x.status='Needs clarification';}if(view==='testing')x.kind='Test';if(view==='later'){x.status='Ideas / Later';x.release='Later';}edit(x);};
 const move=async(id:string,status:string)=>{const x=items.find(x=>x.id===id);if(!x||x.status===status)return;try{await save({...x,status,release:status==='Ideas / Later'?'Later':x.release});toast.success('Status updated');}catch(e){toast.error((e as Error).message);}};
 const scoped=items.filter(x=>scope==='All work'||(scope==='Canada / Cameroon later'?canadaOnlyIds.includes(x.id):!canadaOnlyIds.includes(x.id)));
 const pilot=items.filter(x=>pilotFeatureIds.includes(x.id));const done=pilot.filter(x=>['Ready to test','Done'].includes(x.status)).length;const percent=Math.round(done/pilotFeatureIds.length*100);const openDec=items.filter(x=>x.kind==='Decision'&&x.status!=='Done');
 const visible=scoped.filter(x=>(area==='All areas'||x.area===area)&&(priority==='All priorities'||x.priority===priority)&&`${x.id} ${x.title} ${x.description} ${x.owner}`.toLowerCase().includes(query.toLowerCase())).filter(x=>view==='decisions'?x.kind==='Decision':view==='testing'?['Test','Bug'].includes(x.kind):view==='later'?x.release==='Later':(scope==='Canada / Cameroon later'||x.release==='MVP')&&x.kind!=='Decision');
 const titles:Record<string,string>={board:'Development board',decisions:'Decision log',testing:'Testing & issues',later:'Ideas for later',pilot:'Pilot readiness'};
 const counts:Record<string,number>={board:items.filter(x=>x.release==='MVP'&&x.kind!=='Decision').length,decisions:items.filter(x=>x.kind==='Decision').length,testing:items.filter(x=>['Test','Bug'].includes(x.kind)).length,later:items.filter(x=>x.release==='Later').length};
 return <div className="app"><Toaster richColors position="bottom-right"/><header className="masthead"><a className="brand" href="/" aria-label="Buildroom home"><span className="logo"><i/><i/><i/></span>buildroom<span className="brand-divider"/> <span className="project-name">Investment platform</span></a><span className="private"><LockKeyhole size={14}/> Private workspace</span></header>
 <main><section className="intro"><div><div className="eyebrow">PRODUCT DEVELOPMENT <span>/</span> RELEASE 01</div><h1>Mola development workspace</h1><p>Implementation, group setup and follow-up issues for the first Mola pilot.</p></div><button className="primary" onClick={add} disabled={loading||!!error}><Plus size={18}/> New item</button></section>
 <section className="summary"><div className="release-card"><div className="summary-label"><Flag size={16}/> Mola pilot implementation <span>{loading?'—':percent+'%'}</span></div><Progress value={percent} aria-label="Mola pilot implementation progress"/><div className="small-meta">{loading?'Loading feature status…':`${done} of ${pilotFeatureIds.length} pilot features implemented`} <span>Member testing deferred</span></div></div><button className="stat" onClick={()=>setView('decisions')}><span className="stat-icon amber"><CircleHelp size={20}/></span><div><strong>{loading?'—':openDec.length}</strong><span>Decisions to resolve</span></div><ArrowUpRight size={16}/></button><button className="stat" onClick={()=>setView('testing')}><span className="stat-icon blue"><CheckCheck size={20}/></span><div><strong>{loading?'—':items.filter(x=>['Test','Bug'].includes(x.kind)&&x.status!=='Done').length}</strong><span>Tests & issues open</span></div><ArrowUpRight size={16}/></button></section>
 <section className="workspace"><div className="viewbar"><Tabs value={view} onValueChange={setView}><TabsList variant="line">{[['board','Board',LayoutGrid],['decisions','Decisions',FileCheck2],['testing','Testing',CheckCheck],['pilot','Pilot',ClipboardList],['later','Later',Lightbulb]].map(([v,t,I]:any)=><TabsTrigger key={v} value={v}><I size={16}/>{t}{v!=='pilot'&&<span className="tab-count">{counts[v]}</span>}</TabsTrigger>)}</TabsList></Tabs><button className="icon-button" aria-label="Refresh board" onClick={load}><RefreshCw size={17}/></button></div>
 <div className="toolbar"><h2>{titles[view]}</h2>{view!=='pilot'&&<div className="filters"><Choice label="Project focus" value={scope} onChange={setScope} options={['Mola first','Canada / Cameroon later','All work']}/><label className="search"><Search size={16}/><input aria-label="Search items" placeholder="Search items…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={14}/></button>}</label><Choice label="Filter by area" value={area} onChange={setArea} options={['All areas',...areas]}/><Choice label="Filter by priority" value={priority} onChange={setPriority} options={['All priorities','High','Medium','Low']}/></div>}</div>
 {view==='decisions'&&<p className="view-note">Agreed requirements and open questions. A recorded decision does not mean its feature has been built.</p>}{view==='testing'&&<p className="view-note">Record the result and evidence in each item before marking it done. Use fictional financial data.</p>}{view==='later'&&<p className="view-note">Keep promising ideas here without expanding the first release.</p>}
 {error?<div className="empty error" role="alert"><h3>We couldn’t load the board</h3><p>{error}</p><button className="secondary" onClick={load}>Try again</button></div>:loading?<div className="empty">Loading your workspace…</div>:view==='pilot'?<div className="pilot-workspace"><PilotReadiness onOpen={id=>{const item=items.find(x=>x.id===id);if(item)edit(item);}} disabled={loading||!!error}/><MobileAcceptance/><PilotRunbook onOpen={()=>{const item=items.find(x=>x.id==='DEV-053');if(item)edit(item);}} disabled={loading||!!error}/><EvidenceCapture items={items} save={save} disabled={loading||!!error}/></div>:view==='board'?<div className="board" aria-label="Development Kanban board">{statuses.filter(s=>s!=='Ideas / Later').map((s,i)=><section className={'column column-'+i} key={s} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag)move(drag,s);setDrag(null);}}><div className="column-heading"><span className="status-mark"/><h3>{s}</h3><span className="column-count">{visible.filter(x=>x.status===s).length}</span><button aria-label={'Add item to '+s} onClick={()=>edit({...fresh(),status:s})}><Plus size={16}/></button></div><div className="cards">{visible.filter(x=>x.status===s).map(x=><button draggable onDragStart={()=>setDrag(x.id)} onDragEnd={()=>setDrag(null)} className="task-card" key={x.id} onClick={()=>edit(x)}><div className="card-top"><span>{x.id}</span><span className={'priority '+x.priority.toLowerCase()}>{x.priority}</span></div><h4>{x.title}</h4><p>{x.description}</p><div className="card-bottom"><span className={'area area-'+x.area.toLowerCase()}>{x.area}</span><span className="owner" title={x.owner||'Unassigned'}>{x.owner?x.owner.split(' ').map(s=>s[0]).slice(0,2).join(''):'—'}</span></div>{x.kind!=='Task'&&<span className="kind-tag">{x.kind}</span>}</button>)}{!visible.some(x=>x.status===s)&&<div className="column-empty">{s==='Done'?'Completed work lands here.':s==='Ready to test'?'Ready when the build is.':s==='In progress'?'Choose the next task to start.':'No matching items.'}</div>}</div></section>)}</div>:<div className="record-list">{visible.map(x=><button className="record" key={x.id} onClick={()=>edit(x)}><span className={'record-symbol '+(x.status==='Done'?'resolved':'')}><ClipboardList size={20}/></span><div><div className="record-meta">{x.id} · {x.area} · {x.kind}</div><h3>{x.title}</h3><p>{x.description}</p></div><span className={'record-status '+(x.status==='Done'?'resolved':'')}>{x.kind==='Decision'&&x.status==='Done'?'Decided':x.status}</span><ArrowUpRight size={18}/></button>)}{!visible.length&&<div className="empty">No matching items. Adjust your filters or add a new item.</div>}</div>}
 </section><ReleaseHistory/><footer><span>Investment platform · MVP workspace</span><span>Development planning only · No financial records</span></footer></main>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!saving)setDraft(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>{draft?.id||'New item'}</DialogTitle><DialogDescription>{draft?.id?'Update the task, decisions, and evidence.':'Capture a task, question, test, or future idea.'}</DialogDescription></DialogHeader>{draft&&<form onSubmit={async e=>{e.preventDefault();setSaving(true);setSaveError('');try{await save(draft);setDraft(null);toast.success('Item saved');}catch(e){setSaveError((e as Error).message);}finally{setSaving(false);}}}><label className="field">Title<input required maxLength={180} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="What needs to happen?"/></label><div className="field-grid">{[['kind','Type',kinds],['status','Status',statuses],['area','Area',areas],['priority','Priority',['High','Medium','Low']],['release','Release',['MVP','Later']]].map(([key,label,opts]:any)=><label className="field" key={key}>{label}<Choice label={label} value={(draft as any)[key]} onChange={v=>setDraft({...draft,[key]:v,...(key==='status'&&v==='Ideas / Later'?{release:'Later'}:{})})} options={opts}/></label>)}<label className="field">Owner<input value={draft.owner} placeholder="Unassigned" onChange={e=>setDraft({...draft,owner:e.target.value})}/></label></div><label className="field">Purpose / description<textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field">Acceptance criteria<textarea rows={4} placeholder="One check per line" value={draft.criteria} onChange={e=>setDraft({...draft,criteria:e.target.value})}/></label><div className="field-grid two"><label className="field">Dependencies<input placeholder="Task IDs or decisions needed" value={draft.dependencies} onChange={e=>setDraft({...draft,dependencies:e.target.value})}/></label><label className="field">Target date<input type="date" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></label></div><label className="field">Notes / test evidence<textarea rows={3} placeholder="Results, reproduction steps, or links to screenshots. No sensitive data." value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>{saveError&&<p role="alert" className="save-error">{saveError}</p>}<div className="editor-footer"><span>{draft.updated?'Updated '+new Date(draft.updated).toLocaleDateString(): 'Saved to your private workspace'}</span><button type="button" className="secondary" disabled={saving} onClick={()=>setDraft(null)}>Cancel</button><button type="submit" className="primary" disabled={saving}>{saving?'Saving…':'Save item'}</button></div></form>}</DialogContent></Dialog>
 </div>
}
