import {CheckCircle2,ClipboardCheck,LockKeyhole} from 'lucide-react';

const gates=[
 {id:'DEV-087',title:'Configure pilot members',state:'Needs setup',detail:'In Mola Members, choose “Link my founder account” and select your actual slot. Then configure one contributor and a different reviewer with agreed permissions. The dated October 4 audit found 0 of 8 founders enabled or linked; Members shows the current counts.'},
 {id:'DEV-093',title:'Check the saved onboarding setup',state:'Owner check available',detail:'In Mola Members, open Pilot onboarding checks. It reads the saved setup and verifies email sign-in, signup and confirmation flags with the provider. Sender, return links and inbox delivery remain separate acceptance checks.'},
 {id:'DEV-065',title:'Verify the sender and email delivery',state:'Delivery unverified',detail:'The October 4 live provider check confirms email signup is enabled and confirmation is required. It does not expose SMTP or the return-link allowlist. Verify those settings, then confirm actual signup, resend and recovery emails arrive and their links work for the intended members.'},
 {id:'DEV-094',title:'Allow the named pilot users',state:'Needs member names',detail:'The Site audience is still owner-only. Configure the agreed contributor and different reviewer in Members, then explicitly allow only the named users through Site sharing. App membership does not grant Site access, and no invitations have been sent.'},
 {id:'DEV-050',title:'Record the weekly cycle',state:'Needs group setup',detail:'No schedule or cutoff was configured in the October 4 audit. Agree the first due date, rate, cutoff time and time zone before generating a pilot cycle.'},
 {id:'DEV-041',title:'Complete collection-account setup',state:'Needs bank setup',detail:'The audit found no collection-account label or holder. Finish the group’s business-bank setup and record masked labels; receipt verification and money movement remain external.'},
 {id:'DEV-083',title:'Review the membership agreement',state:'Needs group text',detail:'Versioned publication and own-founder acceptance are implemented and tested. The group must supply its actual text and decision reference, then each founder reviews and accepts the published version.'},
 {id:'DEV-058',title:'Desktop, phone and member follow-up',state:'Deferred by owner',detail:'The owner reports successful sign-in and has chosen to continue the pilot without waiting for browser or real-member tests. Record issues and actual outcomes when these checks are resumed. This is not a passing test result.'},
 {id:'DEV-061',title:'Agree funding approvers',state:'Needs group decision',detail:'No designated approval rule was configured in the audit. Record the agreed founder count and designated approvers before testing funding authorization. Bank transfers remain external.'}
];

export default function PilotReadiness({onOpen,disabled}:{onOpen:(id:string)=>void;disabled:boolean}){
 return <section className="pilot-readiness" aria-labelledby="pilot-readiness-title">
  <div className="pilot-readiness-header"><div><div className="eyebrow">SMALL MOLA PILOT <span>/</span> READINESS REVIEW</div><h2 id="pilot-readiness-title">Pilot implementation & group setup</h2></div><span className="readiness-pending"><LockKeyhole size={14}/> Testing deferred</span></div>
  <p className="readiness-evidence"><CheckCircle2 size={18}/><span>All <strong>44 pilot behavioral suites</strong> pass, including owner-only onboarding diagnostics, organization branding, payment retry conflicts, safe review corrections, founder linking, email sessions, agreement acceptance, financial workflows and backups. Browser and real-member testing are deferred by owner decision. Group details and named private Site access remain setup actions; email delivery is unverified.</span></p>
  <p className="readiness-evidence">In Mola, open <strong>Pilot setup</strong> to link your founder entry and prepare members, weekly dues, collection details, the agreement and funding approvers in one place. The progress bar counts saved preparation; first sign-ins and individual agreement acceptance remain visible separately.</p><div className="readiness-gates">{gates.map(gate=><article key={gate.id}><div><h3>{gate.title}</h3><span>{gate.state}</span></div><p>{gate.detail}</p><button type="button" className="text-button" disabled={disabled} onClick={()=>onOpen(gate.id)}>Open {gate.id}</button></article>)}</div>
  <details className="readiness-snapshot"><summary>Audit snapshot and pilot scope · October 4, 2026</summary><p>Both Sites remain owner-private. The live audit found one confirmed, previously signed-in Auth account, 0 enabled/linked Mola founders, no weekly schedule, collection labels, agreement draft or designated approvers. The owner installation already uses Supabase, so no owner migration is needed. These are dated observations; Mola Members can recheck saved setup and provider flags.</p><p>Start with contribution tracking and independent review using external payment evidence. D1 is the active ledger. The PostgreSQL adapter and reconciled cutover remain separate work under DEV-066; do not switch storage to begin this pilot. Ownership units, connected payments, and AI are not part of this slice.</p><p>The provider reports email sign-in enabled, signup enabled and email confirmation required. Recent Auth logs show existing-account reads and token events, which do not prove delivery. Verify a custom SMTP sender and the exact confirmation/recovery return URLs before member onboarding; the public settings check cannot read those private settings.</p><p>October 4 owner decision: the owner reports successful sign-in and has deferred browser and real-member testing. DEV-096 supersedes the earlier browser handoff and release-gate wording in DEV-095, DEV-058 and DEV-053. Continue the pilot implementation and record member issues as they arise. The private Site audience still requires named users before others can open it.</p></details>
  <div className="readiness-footer"><span><ClipboardCheck size={16}/> Deferred checks and later member issues stay recorded in DEV-053.</span><button className="secondary" type="button" disabled={disabled} onClick={()=>onOpen('DEV-053')}>Open pilot follow-up</button></div>
 </section>;
}
